# Generated by Django 5.1 on 2024-10-22 17:27

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_reference', models.CharField(max_length=30)),
                ('job_number', models.CharField(blank=True, max_length=30, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
                ('vat_value', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_booking_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_booking_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Booking',
                'verbose_name_plural': 'Equipment Bookings',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('mount', models.CharField(blank=True, max_length=15, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('DEPRECIATED', 'Depreciated'), ('MISSING', 'Missing'), ('POOL', 'Pool'), ('REPAIR', 'Repair'), ('SOLD', 'Sold')], default='POOL')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=13, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.FloatField(default=0.0)),
                ('depreciation_method', models.CharField(blank=True, choices=[('DECLINING-BALANCE', 'Declining Balance'), ('STRAIGHT-LINE', 'Straight Line'), ('SUM-OF-YEARS', 'Sum of Years'), ('UNITS-OF-PRODUCTION', 'Units of Production')], default='DECLINING-BALANCE', null=True)),
                ('hire_day_rate', models.FloatField(default=0.0)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('service_interval_period', models.DurationField(blank=True, choices=[(datetime.timedelta(days=30), '1 Month'), (datetime.timedelta(days=90), '3 Months'), (datetime.timedelta(days=180), '6 Months'), (datetime.timedelta(days=365), '1 Year')], null=True)),
                ('service_due_date', models.DateField(blank=True, null=True)),
                ('retired', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_updated_by', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.manufacturer')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'permissions': [('assign_item', 'Can assign an item to individual.')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentBookingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(default=0.0)),
                ('equipment_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='equipment.equipmentbooking')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_items', to='equipment.item')),
            ],
            options={
                'verbose_name': 'Equipment Booking Item',
                'verbose_name_plural': 'Equipment Booking Items',
                'unique_together': {('equipment_booking', 'item')},
            },
        ),
    ]
